### ISSUE TITLE
Running grist when sourmash is installed via conda (sourmash_env)

### ISSUE THREAD

**Issue by padbc** [dib-lab/genome-grist#143]
Hello all,

Thank you for developing this great tool. My question is straightforward: how can I run grist after installing sourmash 4.2 via 
`conda create -n sourmash_env -c conda-forge -c bioconda sourmash python=3.7`?

The issue is that, after activating the grist environment,  `genome-grist run` throws the following: `sourmash: error: argument cmd: invalid choice: 'sketch'` -- i.e. it uses an older version of `sourmash`.

**Comment by ctb** [comment]
hi @padbc actually genome-grist doesn't install sourmash in its environment (it shouldn't and it doesn't, as far as I can tell :). So I suspect you may be getting a version of sourmash from the base environment?

to debug, can you report the output of `type sourmash`?

to fix, it is totally ok to just conda install the latest version of sourmash. genome-grist won't mind!

let me know if that doesn't work!

**Comment by ctb** [comment]
(And you might also want to figure out where the old version of sourmash is coming from and upgrade it!)

**Comment by padbc** [comment]
That was fast; thank you! So the output of `type sourmash` from the base environment is `sourmash is /home/mixtures/anaconda2/bin/sourmash`

(Conda-installing the latest version of sourmash is what I did: I used `conda create -n sourmash_env -c conda-forge -c bioconda sourmash python=3.7`)

**Comment by ctb** [comment]
right - but that's putting it in `sourmash_env`. you also want it in the grist environment, too, so something like:
```
conda activate grist
conda install -c conda-forge -c bioconda sourmash
```

It will not cause problems there. (Well, shouldn't, at least. I've given up on making strong predictions about what computers will do :)

**Comment by padbc** [comment]
Putting sourmash in the `grist` environment installs the latest version. But grist still looks for the "base" (older) version of sourmash. The way I got here? I first installed sourmash using the default bioconda method, which installed v. 3.2, presumably because I have an older version of python, then grist, etc. I can think of a couple of solutions, but they are probably not ideal. Thanks again.

**Comment by ctb** [comment]
> The issue is that, after activating the grist environment, `genome-grist run` throws the following: `sourmash: error: argument cmd: invalid choice: 'sketch'` -- i.e. it uses an older version of `sourmash`.

if, in the grist conda environment, you've installed an updated version of sourmash but running `sourmash` still runs the old version from the base environment, then something has gone wonky with conda; it has happened to me occasionally. Usually I log out and log back in and it works fine.

(genome-grist itself installs its own versions of sourmash in snakemake-managed environments, incidentally.)

If, after all of that, it still isn't working, I can help you debug - but it's going to come down to looking closely at your PATH variable, I'm afraid, to figure out why conda says its installing sourmash in an environment and then doesn't run it from that environment...

**Comment by ctb** [comment]
(if you can paste in some screenshots or text grabs of the commands you're running and the prompts that result, it might help - you could just be running some stuff out of order, for example, but I can't tell without seeing the output!)

**Comment by padbc** [comment]
To clarify:
>If, in the grist conda environment, you've installed an updated version of sourmash but running sourmash still runs the old version from the base environment 

Running `sourmash` after activating grist actually produces the expected output:

1. `conda activate grist`
2. `sourmash`
>== This is sourmash version 4.2.3. ==

But running `genome-grist run conf-tutorial.yml summarize_mapping` (I'm following the tutorial) produces (I just noticed the "not a conda environment"): 

>Activating conda environment: /home/mixtures/grist/.snakemake/conda/ac2322cb2b4eab44786a3775e1340c01
Not a conda environment: /home/mixtures/grist/.snakemake/conda/ac2322cb2b4eab44786a3775e1340c01
sourmash: error: argument cmd: invalid choice: 'sketch' (choose from 'categorize', 'compare', 'compute', 'dump', 'gather', 'import_csv', 'index', 'info', 'migrate', 'multigather', 'plot', 'sbt_combine', 'search', 'watch', 'lca', 'sig', 'storage')
[Thu Jan 27 15:01:24 2022]
Error in rule smash_abundtrim_wc:
    jobid: 6
    output: outputs.tutorial/sigs/SRR5950647.abundtrim.sig
    conda-env: /home/mixtures/grist/.snakemake/conda/ac2322cb2b4eab44786a3775e1340c01
    shell:

        sourmash sketch dna -p k=21,k=31,k=51,scaled=1000,abund            outputs.tutorial/abundtrim/SRR5950647.abundtrim.fq.gz -o outputs.tutorial/sigs/SRR5950647.abundtrim.sig            --name SRR5950647

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

>Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/mixtures/grist/.snakemake/log/2022-01-27T150123.811376.snakemake.log
Error in snakemake invocation: Command '['snakemake', '-s', '/home/mixtures/anaconda2/envs/grist/lib/python3.10/site-packages/genome_grist/conf/Snakefile', '-j', '1', '--use-conda', 'summarize_mapping', '--configfile', '/home/mixtures/anaconda2/envs/grist/lib/python3.10/site-packages/genome_grist/conf/defaults.conf', '/home/mixtures/anaconda2/envs/grist/lib/python3.10/site-packages/genome_grist/conf/system.conf', 'conf-tutorial.yml']' returned non-zero exit status 1.

**Comment by ctb** [comment]
ohhhhhh.... ok, that's annoying :).

My best guess is there might be some incompatibility with snakemake and the version of conda you have installed. The '` /home/mixtures/grist/.snakemake/conda/ac2322cb2b4eab44786a3775e1340c01` is not a conda environment' is a (and probably THE) problem (and will cause other things to fail down the road, too).

🤔 

You might try deleting the `/home/mixtures/grist/.snakemake/conda/ac2322cb2b4eab44786a3775e1340c01` directory, but presumably it was freshly created. So.

What happens if you try `conda activate /home/mixtures/grist/.snakemake/conda/ac2322cb2b4eab44786a3775e1340c01`?

I'm not sure how anaconda interfaces with snakemake. Is it a recent install? One thought is to try upgrading your conda in your anaconda - something like `conda update -n base conda`.

Alternatively you could try installing a parallel miniforge or mamba forge just to see if that works. Ugh.  Not sure what to do here.

**Comment by padbc** [comment]
Update: I was able to make grist by installing it under miniconda3. I will close this for now, and open a new issue separately. Thanks so much for your help.
