### ISSUE TITLE
How to use grist with my own files

### ISSUE THREAD

**Issue by padbc** [dib-lab/genome-grist#154]
I am trying to run grist on my own files -- i.e. circumventing the "download_sra_wc" rule. If I follow the "Where to insert your own files" instructions verbatim, I get the following "error": `warn: nothing found for {sampleid}`, etc. If I'm missing something obvious, I would be grateful for your help. Thanks!

**Comment by ctb** [comment]
yeah, I was thinking we need to be more explicit.

If you want to circumvent downloading from the SRA, create a file

```
outputs.project/abundtrim/NAME.abundtrim.fq.gz
```
where NAME is the sample name.

If (when? :) that works, please leave this issue open and I'll update the documentation to match more clearly. The `{sample}` is a nod to how Python and snakemake do templating and wildcard matching, and it is not helpful documentation practice, my apologies 😅

**Comment by padbc** [comment]
Thank you! Your suggestion produced the same error. Here are my config and log files:

[conf-tutorial-mtx.txt](https://github.com/dib-lab/genome-grist/files/7990100/conf-tutorial-mtx.txt)
[2022-02-02T124217.723299.snakemake.log](https://github.com/dib-lab/genome-grist/files/7990091/2022-02-02T124217.723299.snakemake.log)

**Comment by ctb** [comment]
hmm, ok - what happens if you do
```
mkdir -p outputs.tutorial.mtx/abundtrim/
touch outputs.tutorial.mtx/abundtrim/Mock_T0_1_S1.abundtrim.fq.gz
```
? that works for me, using your config file.

**Comment by padbc** [comment]
Thank you -- that worked, yes! (I realized later that this scenario is explained in the podar-ref tutorial.)

What I'm confused about, then, is naming convention/sample handling. My samples are associated with left (_1) and right (_2) fastq files. Should the config file then specify (following the scenario above)  `Mock_T0_1_S1_1` (R1) and  `Mock_T0_1_S1_2` (R2)? 

In terms of sample handling, it would be great to be able to read in a file of file names for an arbitrary number of fastq files (if this is not possible already, though I don't see a way to this without modifying the snakefile).

**Comment by ctb** [comment]
yay, glad it worked!

These are great ideas for documentation improvement - will work on them.

In the meantime:
* you should interleave your R1 and R2 files and then put that in as the abundtrim file. The mapping software currently only does single-end mapping anyway (another thing I should document).
* for many samples, I just put them in a YAML list:
```
samples:
- sample1
- sample2
- sample3
```

and so far that's been sufficient. Would that work for you? I worry about having too many different sources of info for the config file! But it would be easy to add a "sample list file" to the config.

**Comment by padbc** [comment]
Excellent, thank you. Listing the samples in a YAML list is absolutely fine. One scenario where I envision the ability to handle several (dozens/hundreds) of samples is if grist is used for taxonomic classification, as explained in the biorXiv paper.

**Comment by ctb** [comment]
absolutely. let me know when the YAML format becomes burdensome :).

The taxonomy reporting in grist itself is not very advanced or manicured, although it does automagically provide sourmash taxonomy report in `{outputs}/gather/{sample}.gather.with-lineages.csv`. I'd love suggestions on what kind of rollup summaries would be good, if and as you think of them.

**Comment by ctb** [comment]
FYI I've updated the documentation and provided a `prevent_sra_dowload` config option over in https://github.com/dib-lab/genome-grist/pull/157. Cutting a new release shortly.

**Comment by ctb** [comment]
released as https://github.com/dib-lab/genome-grist/releases/tag/v0.8.2

**Comment by ctb** [comment]
closing for now. Reopen as you have questions and thoughts, or create a new issue - whichever you prefer!

**Comment by ctb** [comment]
Yep! is updated [here](https://dib-lab.github.io/genome-grist/configuring/#analyzing-your-own-metagenomes):

>Analyzing your own metagenomes

You can provide a list of SRA run accessions in the samples: list in the config file, and genome-grist will automatically download, interleave, and trim them for you.

If you want to run genome-grist on your own metagenomes, you need to provide one FASTQ file per sample in the trim/ subdirectory of the output directory; for example, for the output directory outputs.private and the sample named podar, you would need to create outputs.private/trim/podar.trim.fq.gz. This should be an interleaved file of Illumina reads, as generated by (for example) seqtk mergepe. The file must start with the sample name and end in trim.fq.gz.

Providing correctly-named files will shortcut automatic SRA downloads for these files, and genome-grist will download any remaining samples.

If you want to prevent automatic downloading from the SRA completely, you can set the parameter prevent_sra_download: true in the config file. This is a good parameter to set if you are only analyzing your own prepared data!
