### ISSUE TITLE
trim-low-abund defaults to a k-mer size of 32

### ISSUE THREAD

**Issue by jeanzzhao** [dib-lab/genome-grist#191]
Not sure why kmer size = 32 not 31 in one of my genome-grist run log file `grun.log` under `zyzhao@farm:~/assembly-loss/grist` folder.
<img width="904" alt="Screen Shot 2022-07-14 at 2 53 13 PM" src="https://user-images.githubusercontent.com/93946648/179093748-2012d1e4-0615-44ad-964d-ae6424883a01.png">

**Comment by ctb** [comment]
thanks, @jeanzzhao ! this happens because we do not specify the k-mer size when we call trim-low-abund.py, and so it defaults to k=32. I'll fix it in a bit.

**Comment by ctb** [comment]
Fixed by #218!

Note, this should have minimal effect on results unless you're doing spacegraphcats, per discussion in https://github.com/dib-lab/genome-grist/issues/197. No need to rerun things IMO.
