### ISSUE TITLE
genome-grist failing with empty prefetch_csv

### ISSUE THREAD

**Issue by jeanzzhao** [dib-lab/genome-grist#194]
One of my genome-grist runs failed with empty prefetch_csv. It would be nice to print a more informative notification/error message to give folks an idea of why it’s failing and/or the reason for keeping failing!

**Comment by jeanzzhao** [comment]
You may refer section 1.3.2) on [this note](https://hackmd.io/bD5vRF39QvCq32OVD2qmxQ?view) for details

**Comment by jeanzzhao** [comment]
<img width="1219" alt="Screen Shot 2022-08-05 at 4 45 25 PM" src="https://user-images.githubusercontent.com/93946648/184204713-ea6a8457-d746-46db-97d5-e9079e0ce02d.png">

**Comment by ctb** [comment]
I think one possible resolution to this would be to have the relevant rule in the Snakefile do a `touch` to create an empty CSV file (or one with the right headers - whichever). Alternatively we could add a workflow-friendly option to sourmash to say, look, create an empty file even if there are no matches.

I'll give the first idea a try and see what happens...

**Comment by ctb** [comment]
hi @jeanzzhao this is addressed in #195, although the error reporting in general isn't great...

I've made a few suggestions over in https://github.com/dib-lab/genome-grist/issues/196 about improving the error reporting for errors that occur during snakemake!
