### ISSUE TITLE
should we turn off read trimming/trim-low-abund, or make it optional?

### ISSUE THREAD

**Issue by ctb** [dib-lab/genome-grist#197]
I don't think it's necessary for genome-grist, although it's important for spacegraphcats.

Some of the reasoning is laid out in https://github.com/sourmash-bio/sourmash/issues/2122 -
* erroneous k-mers don't match with anything
* erroneous k-mers are low-abundance and when gather is done with abundance, they don't contribute much to the % matching

and of course for genome-grist, we do mapping, which is also ~robust to mismatches.

We could simply remove it altogether, or we could make it optional. Thoughts?

**Comment by ctb** [comment]
so, more thought -

* trim-low-abund is _really_ slow and I hates it
* I'm not 100% clear on how easy it is to provide an option to disable it in the Snakefile, would need to dig in
* I like having it be an option, but do not think it should be the default

for now, I am thinking I will try to make it an option, and if that doesn't work, I may separate it out into its own and make no trimming the default.

**Comment by ctb** [comment]
see also https://github.com/dib-lab/genome-grist/issues/141

**Comment by ctb** [comment]
#199 feels like a big shift for genome-grist 😓 and I'm not sure how to make a decision.

@taylorreiter @bluegenes any thoughts?

My top two choices are:

1. be lazy and turn off trimming altogether.
2. support trimming as an option, with default=off.

with

3. leave things as they are

a distinct third.

**Comment by ctb** [comment]
Ooh, or an option where trim-low-abund is just run before `make_sgc_conf`. I like that! It would still be an option to run trim-low-abund for steps that make use of it (sgc!), but none of the sourmash or mapping steps would require the abundtrim reads.

**Comment by taylorreiter** [comment]
Has anyone quantified how much the fraction of a metageome covered by a database changes based on abundtrimming? I'm guessing it's a huge change based on distinct k-mers but a small change based on abundance-weighted k-mers. Also how much time savings is this to remove up front abundtrimming? probably fairly substantial.

**Comment by ctb** [comment]
I've implemented full removal over in https://github.com/dib-lab/genome-grist/pull/199. It looks good to me.

I will leave this issue open to report the results above, but I intend to merge #199 soon :).

**Comment by ctb** [comment]
here are the results!

| metagenome | unweighted match | weighted match |
| -------- | -------- | -------- |
| SRR606249 (podar) | 47.8% | 95.9% |
| SRR1976948 (hu-s1)     | 21.4%     | 68.0%     |
| SRR12324253 (zymo mock) | 16.2% | 96.6% |
| SRR5650070 (p8808mo11/iHMP) | 34.8% | 85.6% |

a few observations -

* the two mock communities, podar and zymo, are (almost) completely matched w/weighting! this is presumably because they're (a) mostly or completely built from organisms in reference databases, and (b) deeply sequence
* but boy are the mock communities not matched unweighted... this is (should be) the effect of sequencing errors
* the iHMP data set is pretty good - 85.6% matched to ref genomes!
* even the hu-s1 (~lowish diversity environmental oil well) data set is ~mostly matched

Note this is with genome-grist v0.9.0, so adapter and quality trimmed _only_.
