### ISSUE TITLE
update docs from *.abundtrim.fq.gz to *.trim.fq.gz name

### ISSUE THREAD

**Issue by jessicalumian** [dib-lab/genome-grist#232]
right now the doc says abundtrim.fq.gz here: https://dib-lab.github.io/genome-grist/configuring/

<img width="845" alt="Screen Shot 2022-09-29 at 12 04 07 PM" src="https://user-images.githubusercontent.com/9140844/193120141-c853b9ab-8f8e-4446-a6a1-b6d18d1be062.png">

I'll make a PR!

**Comment by ctb** [comment]
nice catch!

but!

this was already fixed in https://github.com/dib-lab/genome-grist/pull/199; I was waiting for a release to update the docs!

I have done so now! See https://dib-lab.github.io/genome-grist/configuring/.
