### ISSUE TITLE
custom database

### ISSUE THREAD

**Issue by smb20200615** [dib-lab/genome-grist#28]
Hello,

Thank you so much for your wonderful tool. I was wondering how do we adapt your pipeline if we have a set of isolate genomes that we want to use to query our metagenomes. We have analyzed our isolate genomes and have a VCF file representing all the variants that can be found and want to find the abundance of those strains/variants. Is this at all possible with your tool?

Many thanks in advance,

**Comment by ctb** [comment]
hello and great question!

the input database formats are quite flexible and in the future all you will need to do is add one or more files with "standard" sourmash database formats (collection of signatures, or SBT, or LCA, or directory of signatures), as well as a pointer to a directory with genome files named by accessions.

the tricky bit is that right now we rely 100% on genbank identifiers, but this is just for the moment. we already have ways around this planned (#8 and #13) but I haven't implemented it yet.

I'll dig into this next time I get a chance but it may be a few weeks.

in the meantime, you can use sourmash gather with private database collections just fine! ;).
