### ISSUE TITLE
update sourmash command in docs to include *gz on configuring page

### ISSUE THREAD

**Issue by jessicalumian** [dib-lab/genome-grist#296]
On the genome-grist configuring page: https://dib-lab.github.io/genome-grist/configuring/

the sourmash command to sketch is:

```
sourmash sketch dna -p k=31,scaled=1000
```

I suggest adding *.gz to the end of the command, especially because the one below is `sourmash index output.sbt.zip *.sig`

**Comment by ctb** [comment]
fixed in #299!
