### ISSUE TITLE
how to currently install and run cmds

### ISSUE THREAD

**Issue by marisalim** [dib-lab/genome-grist#37]
To install genome-grist, you currently need to run:

```
git clone https://github.com/dib-lab/genome-grist.git
pip install -e genome-grist
```
As of today, this installation version is v0.6.dev6+g0e772df. 

genome-grist commands need to be run from inside the repo right now, for example:

```
cd genome-grist
genome-grist process HSMA33MX smash_reads
# snakemake workflow should start running
# or you can run the whole test workflow 
make test
# snakemake workflow should start running
```
---
If you use the pip install instructions in the repo README, the installation code will run without error (v0.5). But that installation method is missing the `config.yml` file and you'll get errors like this when you try the quick start command `genome-grist process HSMA33MX smash_reads`:

```
File "/home/mcwlim/miniconda3/envs/grist/lib/python3.7/site-packages/genome_grist/__main__.py", line 77, in run_snakemake
    raise ValueError(f"cannot find config file '{configfile}'")
ValueError: cannot find config file 'conf.yml'
```

**Comment by ctb** [comment]
this has been fixed as of v0.6.1!
