### ISSUE TITLE
why are `checkpoint gather_genbank` and `checkpoint gather_genbank_wc` checkpoints instead of rules?

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/genome-grist#80]
why are [`checkpoint gather_genbank`](https://github.com/dib-lab/genome-grist/blob/804259129af2bd07bd697259e6830ca92bd8c004/genome_grist/conf/Snakefile#L97) and [`checkpoint gather_genbank_wc`](https://github.com/dib-lab/genome-grist/blob/804259129af2bd07bd697259e6830ca92bd8c004/genome_grist/conf/Snakefile#L102) checkpoints instead of rules? 

I understand the purpose of [`Checkpoint_GatherResults`](https://github.com/dib-lab/genome-grist/blob/804259129af2bd07bd697259e6830ca92bd8c004/genome_grist/conf/Snakefile#L108) to dynamically solve for outputs based on accessions in gather results. However, the output of `gather_genbank` and `gather_genbank_wc` are based only on the wildcard `sample`, which is defined in the config and not dynamically altered by an unknown number of outputs in the workflow, so shouldn't/couldn't these checkpoints just be rules?

(wondering if this may be related to #77, and I want to reimplement a class like `Checkpoint_GatherResults` in another workflow so also curious if my mental model is missing something important)

**Comment by taylorreiter** [comment]
Looking at this more, I'm guessing that this part of the class `Checkpoint_GatherResults` requires a checkpoint:
```
    def __call__(self, w):
        global checkpoints

        # wait for the results of 'gather_genbank_wc'; this will trigger
        # exception until that rule has been run.
        checkpoints.gather_genbank_wc.get(**w)

        # parse hitlist_genomes,
        genome_accs = self.get_genome_accs(w.sample)

        p = expand(self.pattern, acc=genome_accs, **w)
        return p
```

And that there's not something similar for rules?

```
    def __call__(self, w):
        global rules

        # wait for the results of 'gather_genbank_wc'; this will trigger
        # exception until that rule has been run.
        rules.gather_genbank_wc.get(**w)

        # parse hitlist_genomes,
        genome_accs = self.get_genome_accs(w.sample)

        p = expand(self.pattern, acc=genome_accs, **w)
        return p
```

And that this is a way to make the class always rely on the gather results existing before trying to solve for output names, and when used in an `output` field of a snakemake rule, it triggers the DAG to always make the output of `gather_genbank_wc` available, essentially as an input to whatever rule, but then you don't have to explicitly write in the gather results as an input?

**Comment by taylorreiter** [comment]
When there's a blog post that you provided feedback on that answers our question
http://ivory.idyll.org/blog/2021-snakemake-checkpoints.html

**Comment by ctb** [comment]
😆
